### ISSUE TITLE
Error sometimes after update

### ISSUE THREAD

**Issue by PikkonMG** [ACastanza/PvpAlerts#3] opened 2023-08-27 04:21 UTC
Error Code 357159FE

user:/AddOns/PvpAlerts/PvpAlerts_3D_System.lua:3798: operator .. is not supported for nil .. string
stack traceback:
user:/AddOns/PvpAlerts/PvpAlerts_3D_System.lua:3798: in function 'FindNearbyPOIs'
user:/AddOns/PvpAlerts/PvpAlerts_3D_System.lua:4237: in function 'PVP:UpdateNearbyKeepsAndPOIs'
user:/AddOns/PvpAlerts/PvpAlerts.lua:127: in function 'PVP.OnUpdate'

**Comment by ACastanza** [comment] 2023-08-27 09:13
Are you completely sure you're running the latest version? Of not, can you
try downloading the latest version and replacing the existing files?

This bug is caused by the game randomly sending incomplete information for
the crossed-swords. I've put in place some workarounds that should solve
it, and haven't seen this error with the latest version. That said, the
error is infrequent so I might've just not encountered it yet. If you're
sure you're up-to-date, I'll take another look and see what I can do to
mitigate the issue.

-Anthony

**Comment by PikkonMG** [comment] 2023-08-27 14:31
Ya I got that error last night after downloading the latest version yesterday. Ill download it and replace files again just incase.

**Comment by ACastanza** [comment] 2023-08-27 18:11
Oh! I never did a "release" for the fix, that's why. The issue is fixed in the main branch, but not in a versioned release, I'll go ahead and do that now.

**Comment by ACastanza** [comment] 2023-08-27 18:14
Okay, the release with that fix is live - https://github.com/ACastanza/PvpAlerts_Patch/releases/tag/U39-V5
Let me know if you still encounter that ui error!

**Comment by ACastanza** [comment] 2023-10-05 17:00
Since I haven't heard back on you here and I haven't seen this error again, I'm going to go ahead and close this issue. Let me know if it pops back up again!

**Closed as completed by ACastanza** 2023-10-05 17:00 UTC
